export enum TransactionTypeEnum {
  ADD_BALANCE = 'ADD_BALANCE',
  TRANSFER = 'TRANSFER',
  VENDOR_TRANSACTION = 'VENDOR_TRANSACTION',
  MISCELLANEOUS_TRANSACTION = 'MISCELLANEOUS_TRANSACTION',
  REFUND = 'REFUND',
}
